# Generated by Django 5.0.1 on 2024-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
