# Generated by Django 5.0.1 on 2024-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0002_category_image_subcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Retypepass', models.CharField(blank=True, max_length=20, null=True)),
                ('Phnumber', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User detail',
            },
        ),
    ]
