# Generated by Django 5.0.1 on 2024-03-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0003_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
