# Generated by Django 5.0.1 on 2024-03-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0004_alter_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('detail', models.TextField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('totalprice', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart_app.product')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart_app.register')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('detail', models.TextField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('totalprice', models.IntegerField()),
                ('conformation', models.BooleanField(default=False)),
                ('delivery', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart_app.product')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecart_app.register')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
