# Generated by Django 5.0.1 on 2024-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart_app', '0005_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
